create table "public"."agent_instances" (
    "id" uuid not null default gen_random_uuid(),
    "thread_id" uuid not null,
    "agent_type" text not null,
    "state" text not null,
    "state_payload" jsonb not null default '{}'::jsonb,
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp with time zone not null default now()
);


create table "public"."event_threads" (
    "id" uuid not null default gen_random_uuid(),
    "session_id" uuid not null,
    "should_proceed" boolean not null default true,
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp with time zone not null default now()
);


create table "public"."events" (
    "id" uuid not null default gen_random_uuid(),
    "thread_id" uuid not null,
    "type" text not null,
    "agent_id" uuid,
    "user_id" uuid,
    "progress" numeric(3,2) not null default 0,
    "payload" jsonb not null default '{}'::jsonb,
    "order_index" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp with time zone not null default now()
);


create table "public"."individual_reports" (
    "id" uuid not null default gen_random_uuid(),
    "participant_user_id" uuid not null,
    "session_id" uuid not null,
    "content_markdown" text not null,
    "created_at" timestamp with time zone not null default now()
);


create table "public"."participant_reflections" (
    "id" uuid not null default gen_random_uuid(),
    "participant_user_id" uuid not null,
    "session_id" uuid not null,
    "text" text not null,
    "created_at" timestamp with time zone not null default now(),
    "submitted_at" timestamp with time zone not null default now()
);


create table "public"."participants" (
    "user_id" uuid not null,
    "session_id" uuid not null,
    "name" character varying(255) not null,
    "latest_individual_report_id" uuid,
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp with time zone not null default now()
);


create table "public"."responses" (
    "id" uuid not null default gen_random_uuid(),
    "participant_user_id" uuid not null,
    "session_id" uuid not null,
    "statement_id" uuid not null,
    "value" integer,
    "created_at" timestamp with time zone not null default now(),
    "response_type" text not null default 'scale'::text,
    "text_response" text
);


create table "public"."session_reports" (
    "id" uuid not null default gen_random_uuid(),
    "session_id" uuid not null,
    "version" integer not null default 1,
    "status" text not null default 'pending'::text,
    "request_markdown" text not null default ''::text,
    "content_markdown" text,
    "prompt_snapshot" jsonb not null default '{}'::jsonb,
    "model" text not null default 'google/gemini-2.5-pro'::text,
    "token_usage" jsonb,
    "error_message" text,
    "created_by" uuid not null,
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp with time zone not null default now(),
    "completed_at" timestamp with time zone
);


create table "public"."sessions" (
    "id" uuid not null default gen_random_uuid(),
    "title" text not null,
    "context" text not null,
    "is_public" boolean not null default true,
    "host_user_id" uuid not null,
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp with time zone not null default now(),
    "goal" text not null default ''::text,
    "admin_access_token" uuid not null default gen_random_uuid()
);


create table "public"."situation_analysis_reports" (
    "id" uuid not null default gen_random_uuid(),
    "session_id" uuid not null,
    "content_markdown" text not null,
    "created_at" timestamp with time zone not null default now()
);


create table "public"."statements" (
    "id" uuid not null default gen_random_uuid(),
    "session_id" uuid not null,
    "text" text not null,
    "order_index" integer not null default 0,
    "created_at" timestamp with time zone not null default now()
);


CREATE UNIQUE INDEX agent_instances_pkey ON public.agent_instances USING btree (id);

CREATE UNIQUE INDEX agent_instances_thread_id_agent_type_key ON public.agent_instances USING btree (thread_id, agent_type);

CREATE INDEX agent_instances_thread_idx ON public.agent_instances USING btree (thread_id);

CREATE UNIQUE INDEX event_threads_pkey ON public.event_threads USING btree (id);

CREATE UNIQUE INDEX event_threads_session_id_key ON public.event_threads USING btree (session_id);

CREATE INDEX event_threads_session_idx ON public.event_threads USING btree (session_id);

CREATE UNIQUE INDEX events_pkey ON public.events USING btree (id);

CREATE INDEX events_thread_order_idx ON public.events USING btree (thread_id, order_index);

CREATE INDEX individual_reports_participant_idx ON public.individual_reports USING btree (participant_user_id, session_id, created_at DESC);

CREATE UNIQUE INDEX individual_reports_pkey ON public.individual_reports USING btree (id);

CREATE UNIQUE INDEX participant_reflections_pkey ON public.participant_reflections USING btree (id);

CREATE INDEX participant_reflections_session_idx ON public.participant_reflections USING btree (session_id, submitted_at DESC);

CREATE UNIQUE INDEX participants_pkey ON public.participants USING btree (user_id, session_id);

CREATE INDEX participants_session_idx ON public.participants USING btree (session_id);

CREATE INDEX responses_participant_idx ON public.responses USING btree (participant_user_id, session_id);

CREATE UNIQUE INDEX responses_participant_user_id_session_id_statement_id_key ON public.responses USING btree (participant_user_id, session_id, statement_id);

CREATE UNIQUE INDEX responses_pkey ON public.responses USING btree (id);

CREATE INDEX responses_statement_idx ON public.responses USING btree (statement_id);

CREATE UNIQUE INDEX session_reports_pkey ON public.session_reports USING btree (id);

CREATE INDEX session_reports_session_idx ON public.session_reports USING btree (session_id, created_at DESC);

CREATE INDEX session_reports_status_idx ON public.session_reports USING btree (status);

CREATE UNIQUE INDEX sessions_admin_access_token_idx ON public.sessions USING btree (admin_access_token);

CREATE INDEX sessions_created_at_idx ON public.sessions USING btree (created_at DESC);

CREATE INDEX sessions_host_user_idx ON public.sessions USING btree (host_user_id);

CREATE UNIQUE INDEX sessions_pkey ON public.sessions USING btree (id);

CREATE UNIQUE INDEX situation_analysis_reports_pkey ON public.situation_analysis_reports USING btree (id);

CREATE INDEX situation_reports_session_idx ON public.situation_analysis_reports USING btree (session_id, created_at DESC);

CREATE UNIQUE INDEX statements_pkey ON public.statements USING btree (id);

CREATE INDEX statements_session_idx ON public.statements USING btree (session_id);

CREATE INDEX statements_session_order_idx ON public.statements USING btree (session_id, order_index);

alter table "public"."agent_instances" add constraint "agent_instances_pkey" PRIMARY KEY using index "agent_instances_pkey";

alter table "public"."event_threads" add constraint "event_threads_pkey" PRIMARY KEY using index "event_threads_pkey";

alter table "public"."events" add constraint "events_pkey" PRIMARY KEY using index "events_pkey";

alter table "public"."individual_reports" add constraint "individual_reports_pkey" PRIMARY KEY using index "individual_reports_pkey";

alter table "public"."participant_reflections" add constraint "participant_reflections_pkey" PRIMARY KEY using index "participant_reflections_pkey";

alter table "public"."participants" add constraint "participants_pkey" PRIMARY KEY using index "participants_pkey";

alter table "public"."responses" add constraint "responses_pkey" PRIMARY KEY using index "responses_pkey";

alter table "public"."session_reports" add constraint "session_reports_pkey" PRIMARY KEY using index "session_reports_pkey";

alter table "public"."sessions" add constraint "sessions_pkey" PRIMARY KEY using index "sessions_pkey";

alter table "public"."situation_analysis_reports" add constraint "situation_analysis_reports_pkey" PRIMARY KEY using index "situation_analysis_reports_pkey";

alter table "public"."statements" add constraint "statements_pkey" PRIMARY KEY using index "statements_pkey";

alter table "public"."agent_instances" add constraint "agent_instances_thread_id_agent_type_key" UNIQUE using index "agent_instances_thread_id_agent_type_key";

alter table "public"."agent_instances" add constraint "agent_instances_thread_id_fkey" FOREIGN KEY (thread_id) REFERENCES event_threads(id) ON DELETE CASCADE not valid;

alter table "public"."agent_instances" validate constraint "agent_instances_thread_id_fkey";

alter table "public"."event_threads" add constraint "event_threads_session_id_fkey" FOREIGN KEY (session_id) REFERENCES sessions(id) ON DELETE CASCADE not valid;

alter table "public"."event_threads" validate constraint "event_threads_session_id_fkey";

alter table "public"."event_threads" add constraint "event_threads_session_id_key" UNIQUE using index "event_threads_session_id_key";

alter table "public"."events" add constraint "events_agent_id_fkey" FOREIGN KEY (agent_id) REFERENCES agent_instances(id) ON DELETE SET NULL not valid;

alter table "public"."events" validate constraint "events_agent_id_fkey";

alter table "public"."events" add constraint "events_thread_id_fkey" FOREIGN KEY (thread_id) REFERENCES event_threads(id) ON DELETE CASCADE not valid;

alter table "public"."events" validate constraint "events_thread_id_fkey";

alter table "public"."individual_reports" add constraint "individual_reports_participant_fk" FOREIGN KEY (participant_user_id, session_id) REFERENCES participants(user_id, session_id) ON DELETE CASCADE not valid;

alter table "public"."individual_reports" validate constraint "individual_reports_participant_fk";

alter table "public"."participant_reflections" add constraint "participant_reflections_participant_fk" FOREIGN KEY (participant_user_id, session_id) REFERENCES participants(user_id, session_id) ON DELETE CASCADE not valid;

alter table "public"."participant_reflections" validate constraint "participant_reflections_participant_fk";

alter table "public"."participants" add constraint "participants_latest_report_fk" FOREIGN KEY (latest_individual_report_id) REFERENCES individual_reports(id) ON DELETE SET NULL not valid;

alter table "public"."participants" validate constraint "participants_latest_report_fk";

alter table "public"."participants" add constraint "participants_session_id_fkey" FOREIGN KEY (session_id) REFERENCES sessions(id) ON DELETE CASCADE not valid;

alter table "public"."participants" validate constraint "participants_session_id_fkey";

alter table "public"."responses" add constraint "responses_participant_fk" FOREIGN KEY (participant_user_id, session_id) REFERENCES participants(user_id, session_id) ON DELETE CASCADE not valid;

alter table "public"."responses" validate constraint "responses_participant_fk";

alter table "public"."responses" add constraint "responses_participant_user_id_session_id_statement_id_key" UNIQUE using index "responses_participant_user_id_session_id_statement_id_key";

alter table "public"."responses" add constraint "responses_response_type_check" CHECK ((response_type = ANY (ARRAY['scale'::text, 'free_text'::text]))) not valid;

alter table "public"."responses" validate constraint "responses_response_type_check";

alter table "public"."responses" add constraint "responses_statement_id_fkey" FOREIGN KEY (statement_id) REFERENCES statements(id) ON DELETE CASCADE not valid;

alter table "public"."responses" validate constraint "responses_statement_id_fkey";

alter table "public"."session_reports" add constraint "session_reports_session_id_fkey" FOREIGN KEY (session_id) REFERENCES sessions(id) ON DELETE CASCADE not valid;

alter table "public"."session_reports" validate constraint "session_reports_session_id_fkey";

alter table "public"."session_reports" add constraint "session_reports_status_check" CHECK ((status = ANY (ARRAY['pending'::text, 'generating'::text, 'completed'::text, 'failed'::text]))) not valid;

alter table "public"."session_reports" validate constraint "session_reports_status_check";

alter table "public"."situation_analysis_reports" add constraint "situation_analysis_reports_session_id_fkey" FOREIGN KEY (session_id) REFERENCES sessions(id) ON DELETE CASCADE not valid;

alter table "public"."situation_analysis_reports" validate constraint "situation_analysis_reports_session_id_fkey";

alter table "public"."statements" add constraint "statements_session_id_fkey" FOREIGN KEY (session_id) REFERENCES sessions(id) ON DELETE CASCADE not valid;

alter table "public"."statements" validate constraint "statements_session_id_fkey";

set check_function_bodies = off;

CREATE OR REPLACE FUNCTION public.broadcast_table_changes()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
declare
  topic text;
begin
  topic := coalesce(TG_ARGV[0], format('table:%s', TG_TABLE_NAME));
  perform realtime.broadcast_changes(
    topic,
    TG_OP,
    TG_OP,
    TG_TABLE_NAME,
    TG_TABLE_SCHEMA,
    NEW,
    OLD
  );
  return null;
end;
$function$
;

grant delete on table "public"."agent_instances" to "anon";

grant insert on table "public"."agent_instances" to "anon";

grant references on table "public"."agent_instances" to "anon";

grant select on table "public"."agent_instances" to "anon";

grant trigger on table "public"."agent_instances" to "anon";

grant truncate on table "public"."agent_instances" to "anon";

grant update on table "public"."agent_instances" to "anon";

grant delete on table "public"."agent_instances" to "authenticated";

grant insert on table "public"."agent_instances" to "authenticated";

grant references on table "public"."agent_instances" to "authenticated";

grant select on table "public"."agent_instances" to "authenticated";

grant trigger on table "public"."agent_instances" to "authenticated";

grant truncate on table "public"."agent_instances" to "authenticated";

grant update on table "public"."agent_instances" to "authenticated";

grant delete on table "public"."agent_instances" to "service_role";

grant insert on table "public"."agent_instances" to "service_role";

grant references on table "public"."agent_instances" to "service_role";

grant select on table "public"."agent_instances" to "service_role";

grant trigger on table "public"."agent_instances" to "service_role";

grant truncate on table "public"."agent_instances" to "service_role";

grant update on table "public"."agent_instances" to "service_role";

grant delete on table "public"."event_threads" to "anon";

grant insert on table "public"."event_threads" to "anon";

grant references on table "public"."event_threads" to "anon";

grant select on table "public"."event_threads" to "anon";

grant trigger on table "public"."event_threads" to "anon";

grant truncate on table "public"."event_threads" to "anon";

grant update on table "public"."event_threads" to "anon";

grant delete on table "public"."event_threads" to "authenticated";

grant insert on table "public"."event_threads" to "authenticated";

grant references on table "public"."event_threads" to "authenticated";

grant select on table "public"."event_threads" to "authenticated";

grant trigger on table "public"."event_threads" to "authenticated";

grant truncate on table "public"."event_threads" to "authenticated";

grant update on table "public"."event_threads" to "authenticated";

grant delete on table "public"."event_threads" to "service_role";

grant insert on table "public"."event_threads" to "service_role";

grant references on table "public"."event_threads" to "service_role";

grant select on table "public"."event_threads" to "service_role";

grant trigger on table "public"."event_threads" to "service_role";

grant truncate on table "public"."event_threads" to "service_role";

grant update on table "public"."event_threads" to "service_role";

grant delete on table "public"."events" to "anon";

grant insert on table "public"."events" to "anon";

grant references on table "public"."events" to "anon";

grant select on table "public"."events" to "anon";

grant trigger on table "public"."events" to "anon";

grant truncate on table "public"."events" to "anon";

grant update on table "public"."events" to "anon";

grant delete on table "public"."events" to "authenticated";

grant insert on table "public"."events" to "authenticated";

grant references on table "public"."events" to "authenticated";

grant select on table "public"."events" to "authenticated";

grant trigger on table "public"."events" to "authenticated";

grant truncate on table "public"."events" to "authenticated";

grant update on table "public"."events" to "authenticated";

grant delete on table "public"."events" to "service_role";

grant insert on table "public"."events" to "service_role";

grant references on table "public"."events" to "service_role";

grant select on table "public"."events" to "service_role";

grant trigger on table "public"."events" to "service_role";

grant truncate on table "public"."events" to "service_role";

grant update on table "public"."events" to "service_role";

grant delete on table "public"."individual_reports" to "anon";

grant insert on table "public"."individual_reports" to "anon";

grant references on table "public"."individual_reports" to "anon";

grant select on table "public"."individual_reports" to "anon";

grant trigger on table "public"."individual_reports" to "anon";

grant truncate on table "public"."individual_reports" to "anon";

grant update on table "public"."individual_reports" to "anon";

grant delete on table "public"."individual_reports" to "authenticated";

grant insert on table "public"."individual_reports" to "authenticated";

grant references on table "public"."individual_reports" to "authenticated";

grant select on table "public"."individual_reports" to "authenticated";

grant trigger on table "public"."individual_reports" to "authenticated";

grant truncate on table "public"."individual_reports" to "authenticated";

grant update on table "public"."individual_reports" to "authenticated";

grant delete on table "public"."individual_reports" to "service_role";

grant insert on table "public"."individual_reports" to "service_role";

grant references on table "public"."individual_reports" to "service_role";

grant select on table "public"."individual_reports" to "service_role";

grant trigger on table "public"."individual_reports" to "service_role";

grant truncate on table "public"."individual_reports" to "service_role";

grant update on table "public"."individual_reports" to "service_role";

grant delete on table "public"."participant_reflections" to "anon";

grant insert on table "public"."participant_reflections" to "anon";

grant references on table "public"."participant_reflections" to "anon";

grant select on table "public"."participant_reflections" to "anon";

grant trigger on table "public"."participant_reflections" to "anon";

grant truncate on table "public"."participant_reflections" to "anon";

grant update on table "public"."participant_reflections" to "anon";

grant delete on table "public"."participant_reflections" to "authenticated";

grant insert on table "public"."participant_reflections" to "authenticated";

grant references on table "public"."participant_reflections" to "authenticated";

grant select on table "public"."participant_reflections" to "authenticated";

grant trigger on table "public"."participant_reflections" to "authenticated";

grant truncate on table "public"."participant_reflections" to "authenticated";

grant update on table "public"."participant_reflections" to "authenticated";

grant delete on table "public"."participant_reflections" to "service_role";

grant insert on table "public"."participant_reflections" to "service_role";

grant references on table "public"."participant_reflections" to "service_role";

grant select on table "public"."participant_reflections" to "service_role";

grant trigger on table "public"."participant_reflections" to "service_role";

grant truncate on table "public"."participant_reflections" to "service_role";

grant update on table "public"."participant_reflections" to "service_role";

grant delete on table "public"."participants" to "anon";

grant insert on table "public"."participants" to "anon";

grant references on table "public"."participants" to "anon";

grant select on table "public"."participants" to "anon";

grant trigger on table "public"."participants" to "anon";

grant truncate on table "public"."participants" to "anon";

grant update on table "public"."participants" to "anon";

grant delete on table "public"."participants" to "authenticated";

grant insert on table "public"."participants" to "authenticated";

grant references on table "public"."participants" to "authenticated";

grant select on table "public"."participants" to "authenticated";

grant trigger on table "public"."participants" to "authenticated";

grant truncate on table "public"."participants" to "authenticated";

grant update on table "public"."participants" to "authenticated";

grant delete on table "public"."participants" to "service_role";

grant insert on table "public"."participants" to "service_role";

grant references on table "public"."participants" to "service_role";

grant select on table "public"."participants" to "service_role";

grant trigger on table "public"."participants" to "service_role";

grant truncate on table "public"."participants" to "service_role";

grant update on table "public"."participants" to "service_role";

grant delete on table "public"."responses" to "anon";

grant insert on table "public"."responses" to "anon";

grant references on table "public"."responses" to "anon";

grant select on table "public"."responses" to "anon";

grant trigger on table "public"."responses" to "anon";

grant truncate on table "public"."responses" to "anon";

grant update on table "public"."responses" to "anon";

grant delete on table "public"."responses" to "authenticated";

grant insert on table "public"."responses" to "authenticated";

grant references on table "public"."responses" to "authenticated";

grant select on table "public"."responses" to "authenticated";

grant trigger on table "public"."responses" to "authenticated";

grant truncate on table "public"."responses" to "authenticated";

grant update on table "public"."responses" to "authenticated";

grant delete on table "public"."responses" to "service_role";

grant insert on table "public"."responses" to "service_role";

grant references on table "public"."responses" to "service_role";

grant select on table "public"."responses" to "service_role";

grant trigger on table "public"."responses" to "service_role";

grant truncate on table "public"."responses" to "service_role";

grant update on table "public"."responses" to "service_role";

grant delete on table "public"."session_reports" to "anon";

grant insert on table "public"."session_reports" to "anon";

grant references on table "public"."session_reports" to "anon";

grant select on table "public"."session_reports" to "anon";

grant trigger on table "public"."session_reports" to "anon";

grant truncate on table "public"."session_reports" to "anon";

grant update on table "public"."session_reports" to "anon";

grant delete on table "public"."session_reports" to "authenticated";

grant insert on table "public"."session_reports" to "authenticated";

grant references on table "public"."session_reports" to "authenticated";

grant select on table "public"."session_reports" to "authenticated";

grant trigger on table "public"."session_reports" to "authenticated";

grant truncate on table "public"."session_reports" to "authenticated";

grant update on table "public"."session_reports" to "authenticated";

grant delete on table "public"."session_reports" to "service_role";

grant insert on table "public"."session_reports" to "service_role";

grant references on table "public"."session_reports" to "service_role";

grant select on table "public"."session_reports" to "service_role";

grant trigger on table "public"."session_reports" to "service_role";

grant truncate on table "public"."session_reports" to "service_role";

grant update on table "public"."session_reports" to "service_role";

grant delete on table "public"."sessions" to "anon";

grant insert on table "public"."sessions" to "anon";

grant references on table "public"."sessions" to "anon";

grant select on table "public"."sessions" to "anon";

grant trigger on table "public"."sessions" to "anon";

grant truncate on table "public"."sessions" to "anon";

grant update on table "public"."sessions" to "anon";

grant delete on table "public"."sessions" to "authenticated";

grant insert on table "public"."sessions" to "authenticated";

grant references on table "public"."sessions" to "authenticated";

grant select on table "public"."sessions" to "authenticated";

grant trigger on table "public"."sessions" to "authenticated";

grant truncate on table "public"."sessions" to "authenticated";

grant update on table "public"."sessions" to "authenticated";

grant delete on table "public"."sessions" to "service_role";

grant insert on table "public"."sessions" to "service_role";

grant references on table "public"."sessions" to "service_role";

grant select on table "public"."sessions" to "service_role";

grant trigger on table "public"."sessions" to "service_role";

grant truncate on table "public"."sessions" to "service_role";

grant update on table "public"."sessions" to "service_role";

grant delete on table "public"."situation_analysis_reports" to "anon";

grant insert on table "public"."situation_analysis_reports" to "anon";

grant references on table "public"."situation_analysis_reports" to "anon";

grant select on table "public"."situation_analysis_reports" to "anon";

grant trigger on table "public"."situation_analysis_reports" to "anon";

grant truncate on table "public"."situation_analysis_reports" to "anon";

grant update on table "public"."situation_analysis_reports" to "anon";

grant delete on table "public"."situation_analysis_reports" to "authenticated";

grant insert on table "public"."situation_analysis_reports" to "authenticated";

grant references on table "public"."situation_analysis_reports" to "authenticated";

grant select on table "public"."situation_analysis_reports" to "authenticated";

grant trigger on table "public"."situation_analysis_reports" to "authenticated";

grant truncate on table "public"."situation_analysis_reports" to "authenticated";

grant update on table "public"."situation_analysis_reports" to "authenticated";

grant delete on table "public"."situation_analysis_reports" to "service_role";

grant insert on table "public"."situation_analysis_reports" to "service_role";

grant references on table "public"."situation_analysis_reports" to "service_role";

grant select on table "public"."situation_analysis_reports" to "service_role";

grant trigger on table "public"."situation_analysis_reports" to "service_role";

grant truncate on table "public"."situation_analysis_reports" to "service_role";

grant update on table "public"."situation_analysis_reports" to "service_role";

grant delete on table "public"."statements" to "anon";

grant insert on table "public"."statements" to "anon";

grant references on table "public"."statements" to "anon";

grant select on table "public"."statements" to "anon";

grant trigger on table "public"."statements" to "anon";

grant truncate on table "public"."statements" to "anon";

grant update on table "public"."statements" to "anon";

grant delete on table "public"."statements" to "authenticated";

grant insert on table "public"."statements" to "authenticated";

grant references on table "public"."statements" to "authenticated";

grant select on table "public"."statements" to "authenticated";

grant trigger on table "public"."statements" to "authenticated";

grant truncate on table "public"."statements" to "authenticated";

grant update on table "public"."statements" to "authenticated";

grant delete on table "public"."statements" to "service_role";

grant insert on table "public"."statements" to "service_role";

grant references on table "public"."statements" to "service_role";

grant select on table "public"."statements" to "service_role";

grant trigger on table "public"."statements" to "service_role";

grant truncate on table "public"."statements" to "service_role";

grant update on table "public"."statements" to "service_role";

CREATE TRIGGER broadcast_agent_instances AFTER INSERT OR DELETE OR UPDATE ON public.agent_instances FOR EACH ROW EXECUTE FUNCTION broadcast_table_changes('agent_instances');

CREATE TRIGGER broadcast_event_threads AFTER INSERT OR DELETE OR UPDATE ON public.event_threads FOR EACH ROW EXECUTE FUNCTION broadcast_table_changes('event_threads');

CREATE TRIGGER broadcast_responses AFTER INSERT OR DELETE OR UPDATE ON public.responses FOR EACH ROW EXECUTE FUNCTION broadcast_table_changes('responses');

-- Grant schema-level permissions to Supabase roles
grant usage on schema public to anon, authenticated, service_role, authenticator;


